//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContextDBEntities : DbContext
    {
        public ContextDBEntities()
            : base("name=ContextDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Amministratore> Amministratore { get; set; }
        public virtual DbSet<Context> Context { get; set; }
        public virtual DbSet<Partecipante> Partecipante { get; set; }
        public virtual DbSet<Utenti> Utenti { get; set; }
        public virtual DbSet<Voti> Voti { get; set; }
    }
}
