//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voti
    {
        public int id { get; set; }
        public int idUt { get; set; }
        public int idPartecipante { get; set; }
    
        public virtual Partecipante Partecipante { get; set; }
        public virtual Utenti Utenti { get; set; }
    }
}
